// Generated by scripts/generate-brand-assets.py. Do not edit by hand.
/**
 * The Mbarĩ mark: the Kikuyu letter ĩ. A stem, crowned by a tilde.
 * Every measure is a ratio of the stem width T (see the brand sheet).
 * Mark units, bounding box top-left at (0, 0).
 */
export const MARK = {
  /** The stem's width. */
  T: 80,
  width: 287.81,
  height: 357.6,
  stem: {x: 103.9, y: 133.6, width: 80, height: 224},
  /** How far the tilde sits above the mark's box when it is off-stage. */
  lift: 128,
} as const;

/** The tilde, as one outlined shape with round ends. */
export const TILDE_PATH = 'M11.95 30.59 L16.88 27.18 L21.99 23.71 L27.3 20.23 L32.82 16.79 L38.58 13.48 L44.58 10.36 L50.85 7.49 L57.4 4.97 L64.22 2.89 L71.29 1.31 L78.55 0.33 L85.9 0 L93.26 0.33 L100.52 1.31 L107.59 2.89 L114.41 4.97 L120.96 7.49 L127.23 10.36 L133.23 13.48 L138.98 16.79 L144.51 20.23 L149.82 23.71 L154.93 27.18 L159.86 30.59 L164.6 33.87 L169.15 36.96 L173.51 39.82 L177.65 42.39 L181.57 44.65 L185.23 46.56 L188.63 48.11 L191.74 49.31 L194.59 50.19 L197.18 50.77 L199.59 51.09 L201.9 51.2 L204.21 51.09 L206.63 50.77 L209.22 50.19 L212.07 49.31 L215.18 48.11 L218.58 46.56 L222.24 44.65 L226.16 42.39 L230.3 39.82 L234.66 36.96 L239.21 33.87 L243.95 30.59 L250.45 27.24 L257.59 25.7 L264.89 26.05 L271.86 28.28 L278 32.23 L282.91 37.65 L286.26 44.15 L287.81 51.29 L287.46 58.59 L285.23 65.55 L281.27 71.7 L275.86 76.61 L270.93 80.02 L265.82 83.49 L260.51 86.97 L254.98 90.41 L249.23 93.72 L243.23 96.84 L236.96 99.71 L230.41 102.23 L223.59 104.31 L216.52 105.89 L209.26 106.87 L201.9 107.2 L194.55 106.87 L187.29 105.89 L180.22 104.31 L173.4 102.23 L166.85 99.71 L160.58 96.84 L154.58 93.72 L148.82 90.41 L143.3 86.97 L137.99 83.49 L132.88 80.02 L127.95 76.61 L123.21 73.33 L118.66 70.24 L114.3 67.38 L110.16 64.81 L106.24 62.55 L102.58 60.64 L99.18 59.09 L96.07 57.89 L93.22 57.01 L90.63 56.43 L88.21 56.11 L85.9 56 L83.59 56.11 L81.18 56.43 L78.59 57.01 L75.74 57.89 L72.63 59.09 L69.23 60.64 L65.57 62.55 L61.65 64.81 L57.51 67.38 L53.15 70.24 L48.6 73.33 L43.86 76.61 L37.36 79.96 L30.22 81.5 L22.91 81.15 L15.95 78.92 L9.81 74.97 L4.89 69.55 L1.55 63.05 L0 55.91 L0.35 48.61 L2.58 41.65 L6.54 35.5 Z';

/**
 * The native splash draws the mark at this scale, centred in the window
 * (res/drawable/splash_mark.xml). The JS launch screen matches it exactly.
 */
export const SPLASH_SCALE = 0.4;

export const BRAND_COLORS = {
  light: {ink: '#10281F', clay: '#D9502B', ground: '#F4EDDF'},
  dark: {ink: '#F4EDDF', clay: '#D9502B', ground: '#0B1A14'},
} as const;
