# The Mbarĩ icon set. One source for the brand sheet and the app.
# 24 x 24 grid, 2 px line, round caps and joins, no fills except where marked.
# Each icon is a list of primitives:
#   ("path", d)  ("pathf", d) filled  ("circle", cx, cy, r)  ("circlef", cx, cy, r) filled  ("rect", x, y, w, h, r)
# Two icons carry the brand's own cue: `community` is two stems under one tilde
# (the family under one voice), and `language` is the tilde itself.

ICONS = {
    # tabs
    "alerts":    [("path", "M6 16v-5a6 6 0 0 1 12 0v5"), ("path", "M4.5 16h15"), ("path", "M10 19.5a2 2 0 0 0 4 0")],
    "community": [("path", "M4 8.5c2.7-3 5.3-3 8 0s5.3 3 8 0"), ("path", "M8 20v-7"), ("path", "M16 20v-4")],
    "replies":   [("rect", 9, 3, 6, 11, 3), ("path", "M5.5 11a6.5 6.5 0 0 0 13 0"), ("path", "M12 17.5V21")],
    "me":        [("circle", 12, 8, 3.5), ("path", "M4.5 20.5c.6-3.7 3.7-6 7.5-6s6.9 2.3 7.5 6")],
    # navigation
    "back":         [("path", "M15 5l-7 7 7 7")],
    "chevronDown":  [("path", "M6 9l6 6 6-6")],
    "chevronRight": [("path", "M9 5l7 7-7 7")],
    "close":        [("path", "M6 6l12 12M18 6L6 18")],
    "plus":         [("path", "M12 5v14M5 12h14")],
    "arrowRight":   [("path", "M5 12h14"), ("path", "M13 6l6 6-6 6")],
    # actions and meaning
    "play":        [("pathf", "M8.5 5.5v13l10.5-6.5z")],
    "link":        [("path", "M10.5 13.5a4 4 0 0 0 5.7 0l2.6-2.6a4 4 0 0 0-5.7-5.7l-.9.9"), ("path", "M13.5 10.5a4 4 0 0 0-5.7 0l-2.6 2.6a4 4 0 0 0 5.7 5.7l.9-.9")],
    "check":       [("path", "M5 12.5l4.5 4.5L19 7.5")],
    "checkCircle": [("circle", 12, 12, 9), ("path", "M8 12.5l2.7 2.7L16 9.5")],
    "info":        [("circle", 12, 12, 9), ("path", "M12 11v5"), ("circlef", 12, 7.8, 1.1)],
    "clock":       [("circle", 12, 12, 9), ("path", "M12 7v5l3 2")],
    "phone":       [("path", "M5.5 4h3.2l1.6 4-2 1.4a11 11 0 0 0 5.3 5.3l1.4-2 4 1.6v3.2a1.8 1.8 0 0 1-1.9 1.8A15.5 15.5 0 0 1 3.7 5.9 1.8 1.8 0 0 1 5.5 4z")],
    "pin":         [("path", "M12 21s6.5-5.6 6.5-10.5a6.5 6.5 0 0 0-13 0C5.5 15.4 12 21 12 21z"), ("circle", 12, 10.5, 2.3)],
    "sliders":     [("path", "M4 7h9M19 7h1M4 17h1M11 17h9"), ("circle", 16, 7, 2.2), ("circle", 8, 17, 2.2)],
    "search":      [("circle", 10.5, 10.5, 6), ("path", "M20 20l-5.2-5.2")],
    "language":    [("path", "M3 12c3-4.6 6-4.6 9 0s6 4.6 9 0")],
    "mail":        [("rect", 3, 5, 18, 14, 2), ("path", "M3.8 7.5L12 13.5l8.2-6")],
}

def svg_inner(name, cls=""):
    out = []
    for p in ICONS[name]:
        k = p[0]
        if k == "path":     out.append(f'<path d="{p[1]}"/>')
        elif k == "pathf":  out.append(f'<path d="{p[1]}" fill="currentColor" stroke="none"/>')
        elif k == "circle": out.append(f'<circle cx="{p[1]}" cy="{p[2]}" r="{p[3]}"/>')
        elif k == "circlef": out.append(f'<circle cx="{p[1]}" cy="{p[2]}" r="{p[3]}" fill="currentColor" stroke="none"/>')
        elif k == "rect":   out.append(f'<rect x="{p[1]}" y="{p[2]}" width="{p[3]}" height="{p[4]}" rx="{p[5]}"/>')
    return "".join(out)

def svg(name, cls="ic"):
    return f'<svg class="{cls}" viewBox="0 0 24 24" aria-hidden="true">{svg_inner(name)}</svg>'

def to_ts():
    """The same set as a TypeScript module for react-native-svg."""
    lines = ["// Generated by brand/source/icons.py. Do not edit by hand.",
             "// 24 x 24 grid, 2 px line, round caps and joins.",
             "export type IconPrimitive =",
             "  | {t: 'path'; d: string; fill?: boolean}",
             "  | {t: 'circle'; cx: number; cy: number; r: number; fill?: boolean}",
             "  | {t: 'rect'; x: number; y: number; width: number; height: number; rx: number};",
             "", "export const ICON_DATA = {"]
    for name, prims in ICONS.items():
        items = []
        for p in prims:
            k = p[0]
            if k == "path":      items.append(f"{{t: 'path', d: '{p[1]}'}}")
            elif k == "pathf":   items.append(f"{{t: 'path', d: '{p[1]}', fill: true}}")
            elif k == "circle":  items.append(f"{{t: 'circle', cx: {p[1]}, cy: {p[2]}, r: {p[3]}}}")
            elif k == "circlef": items.append(f"{{t: 'circle', cx: {p[1]}, cy: {p[2]}, r: {p[3]}, fill: true}}")
            elif k == "rect":    items.append(f"{{t: 'rect', x: {p[1]}, y: {p[2]}, width: {p[3]}, height: {p[4]}, rx: {p[5]}}}")
        lines.append(f"  {name}: [{', '.join(items)}],")
    lines += ["} as const satisfies Record<string, readonly IconPrimitive[]>;", "",
              "export type IconName = keyof typeof ICON_DATA;", ""]
    return "\n".join(lines)
