#!/usr/bin/env python3
"""Generate every Mbarĩ logo asset the app ships, from one geometry.

  python3 -m venv .venv-brand && .venv-brand/bin/pip install fonttools uharfbuzz
  brew install librsvg
  .venv-brand/bin/python scripts/generate-brand-assets.py

Writes:
  src/components/brand/geometry.ts        the mark: a stem and a tilde, in mark units
  src/components/brand/wordmark-data.ts   "Mbarĩ" outlines (Plus Jakarta Sans Bold) with the mark's tilde
  android/app/src/main/res/drawable/      splash_mark, ic_launcher_foreground, ic_launcher_monochrome
  android/app/src/main/res/mipmap-*/      adaptive icon XML and legacy PNG launcher icons
  android/app/src/main/res/values*/       brand and splash colours

The mark is the Kikuyu letter ĩ: a stem of width T, 2.8T tall, and a tilde 2.9T
wide and 0.7T thick, its centreline 1T above the stem, rising 0.32T. The design
lives in ~/Documents/mbari/brand (index.html has the reasoning and the rules).
"""
import math, os, re, subprocess, tempfile

import uharfbuzz as hb
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.recordingPen import DecomposingRecordingPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

RES = f"{ROOT}/android/app/src/main/res"
FONT = f"{RES}/font/plus_jakarta_sans_bold.ttf"
BRAND_TS = f"{ROOT}/src/components/brand"

# Colour: warm near-black ink, one deep maroon accent, warm paper. The night
# ground is near-black with only a trace of green; on it the maroon lifts.
INK, CLAY, MILLET, NIGHT, PAPER = "#1B1712", "#8C2F2B", "#F3EEE6", "#0F1311", "#F9F5EF"
CLAY_ON_DARK = "#C9483D"

# ---------- the mark, in units of the stem width T ----------
T = 80
STEM_H, GAP, TW, TT, TA = 2.8 * T, 1.0 * T, 2.9 * T, 0.7 * T, 0.32 * T


def f(v):
    return f"{v:.2f}".rstrip("0").rstrip(".")


def wave_pts(cx, cy, w, amp, t, n=48, ncap=12):
    """A tilde of constant thickness with round ends, as one polygon (y grows down)."""
    def c(u): return cx - w / 2 + w * u, cy - amp * math.sin(2 * math.pi * u)
    def nt(u):
        dx, dy = w, -amp * 2 * math.pi * math.cos(2 * math.pi * u)
        L = math.hypot(dx, dy)
        return -dy / L, dx / L, dx / L, dy / L
    left, right = [], []
    for i in range(n + 1):
        u = i / n; x, y = c(u); nx, ny, _, _ = nt(u)
        left.append((x - nx * t / 2, y - ny * t / 2)); right.append((x + nx * t / 2, y + ny * t / 2))
    pts = left[:]
    x, y = c(1); nx, ny, tx, ty = nt(1)
    for k in range(1, ncap):
        a = math.pi * k / ncap
        pts.append((x + (-nx * math.cos(a) + tx * math.sin(a)) * t / 2, y + (-ny * math.cos(a) + ty * math.sin(a)) * t / 2))
    pts += right[::-1]
    x, y = c(0); nx, ny, tx, ty = nt(0)
    for k in range(1, ncap):
        a = math.pi * k / ncap
        pts.append((x + (nx * math.cos(a) - tx * math.sin(a)) * t / 2, y + (ny * math.cos(a) - ty * math.sin(a)) * t / 2))
    return pts


def pts_d(pts, sx=1, sy=1, dx=0, dy=0):
    return "M" + " L".join(f"{f(dx + x * sx)} {f(dy + y * sy)}" for x, y in pts) + " Z"


# Mark space with its bounding box's top-left at (0, 0): stem foot on the bottom edge.
_wave = wave_pts(0, -(STEM_H + GAP), TW, TA, TT)
X0, Y0 = min(p[0] for p in _wave), min(p[1] for p in _wave)
MW, MH = max(p[0] for p in _wave) - X0, -Y0
STEM = (-T / 2 - X0, MH - STEM_H, T, STEM_H)               # x, y, width, height
TILDE_D = pts_d(_wave, 1, 1, -X0, -Y0)
SPLASH_SCALE = 0.40  # the splash icon is 288dp and must fit a 192dp circle


def write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(content)


def mark_vector(size, scale, ink, clay, dx=0.0, dy=0.0):
    x = (size - MW * scale) / 2 + dx
    y = (size - MH * scale) / 2 + dy
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate-brand-assets.py. Do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{size}dp"
    android:height="{size}dp"
    android:viewportWidth="{size}"
    android:viewportHeight="{size}">
    <group
        android:translateX="{x:.3f}"
        android:translateY="{y:.3f}"
        android:scaleX="{scale}"
        android:scaleY="{scale}">
        <path android:fillColor="{ink}" android:pathData="M{f(STEM[0])},{f(STEM[1])} h{f(STEM[2])} v{f(STEM[3])} h-{f(STEM[2])} Z" />
        <path android:fillColor="{clay}" android:pathData="{TILDE_D}" />
    </group>
</vector>
'''


def ts_geometry():
    write(f"{BRAND_TS}/geometry.ts", f"""// Generated by scripts/generate-brand-assets.py. Do not edit by hand.
/**
 * The Mbarĩ mark: the Kikuyu letter ĩ. A stem, crowned by a tilde.
 * Every measure is a ratio of the stem width T (see the brand sheet).
 * Mark units, bounding box top-left at (0, 0).
 */
export const MARK = {{
  /** The stem's width. */
  T: {T},
  width: {f(MW)},
  height: {f(MH)},
  stem: {{x: {f(STEM[0])}, y: {f(STEM[1])}, width: {f(STEM[2])}, height: {f(STEM[3])}}},
  /** How far the tilde sits above the mark's box when it is off-stage. */
  lift: {f(T * 1.6)},
}} as const;

/** The tilde, as one outlined shape with round ends. */
export const TILDE_PATH = '{TILDE_D}';

/**
 * The native splash draws the mark at this scale, centred in the window
 * (res/drawable/splash_mark.xml). The JS launch screen matches it exactly.
 */
export const SPLASH_SCALE = {SPLASH_SCALE};

export const BRAND_COLORS = {{
  light: {{ink: '{INK}', clay: '{CLAY}', ground: '{PAPER}'}},
  dark: {{ink: '{MILLET}', clay: '{CLAY_ON_DARK}', ground: '{NIGHT}'}},
}} as const;
""")


def android_resources():
    write(f"{RES}/drawable/splash_mark.xml", mark_vector(288, SPLASH_SCALE, "@color/splash_mark_ink", "@color/brand_clay"))
    # Adaptive icon: 108dp canvas, mark inside the 66dp safe circle.
    write(f"{RES}/drawable/ic_launcher_foreground.xml", mark_vector(108, 0.135, MILLET, CLAY_ON_DARK, 0, -0.4))
    write(f"{RES}/drawable/ic_launcher_monochrome.xml", mark_vector(108, 0.135, "#FFFFFFFF", "#FFFFFFFF", 0, -0.4))
    adaptive = '''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate-brand-assets.py. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
'''
    write(f"{RES}/mipmap-anydpi-v26/ic_launcher.xml", adaptive)
    write(f"{RES}/mipmap-anydpi-v26/ic_launcher_round.xml", adaptive)
    write(f"{RES}/values/colors.xml", f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate-brand-assets.py. -->
<resources>
    <color name="brand_ink">{INK}</color>
    <color name="brand_clay">{CLAY}</color>
    <color name="ic_launcher_background">{INK}</color>
    <color name="splash_background">{PAPER}</color>
    <color name="splash_mark_ink">{INK}</color>
</resources>
''')
    write(f"{RES}/values-night/colors.xml", f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate-brand-assets.py. -->
<resources>
    <color name="splash_background">{NIGHT}</color>
    <color name="splash_mark_ink">{MILLET}</color>
    <color name="brand_clay">{CLAY_ON_DARK}</color>
</resources>
''')

    # Legacy launchers (Android 7.x): a rounded square and a circle, mark ~58% of the height.
    size = 1024
    s = size * 0.58 / MH
    x, y = (size - MW * s) / 2, (size - MH * s) / 2 - 8
    for name, shape in (("ic_launcher", f'<rect width="{size}" height="{size}" rx="228" fill="{INK}"/>'),
                        ("ic_launcher_round", f'<circle cx="{size // 2}" cy="{size // 2}" r="{size // 2}" fill="{INK}"/>')):
        svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}">{shape}'
               f'<g transform="translate({x:.2f} {y:.2f}) scale({s:.5f})">'
               f'<rect x="{f(STEM[0])}" y="{f(STEM[1])}" width="{f(STEM[2])}" height="{f(STEM[3])}" fill="{MILLET}"/>'
               f'<path d="{TILDE_D}" fill="{CLAY_ON_DARK}"/></g></svg>')
        with tempfile.NamedTemporaryFile("w", suffix=".svg", delete=False) as tmp:
            tmp.write(svg)
        for density, px in (("mdpi", 48), ("hdpi", 72), ("xhdpi", 96), ("xxhdpi", 144), ("xxxhdpi", 192)):
            os.makedirs(f"{RES}/mipmap-{density}", exist_ok=True)
            subprocess.run(["rsvg-convert", "-w", str(px), "-h", str(px), tmp.name, "-o", f"{RES}/mipmap-{density}/{name}.png"], check=True)
        os.unlink(tmp.name)


# ---------- the wordmark: "Mbarĩ" in Plus Jakarta Sans Bold, with the mark's tilde ----------
def wordmark(text="Mbarĩ", track=-14):
    font = TTFont(FONT)
    gs, order = font.getGlyphSet(), font.getGlyphOrder()
    hbfont = hb.Font(hb.Face(hb.Blob.from_file_path(FONT)))
    buf = hb.Buffer(); buf.add_str(text); buf.guess_segment_properties()
    hb.shape(hbfont, buf, {"kern": True, "liga": False})

    def contours(name):
        pen = DecomposingRecordingPen(gs); gs[name].draw(pen)
        out, cur = [], []
        for op, args in pen.value:
            cur.append((op, args))
            if op in ("closePath", "endPath"):
                out.append(cur); cur = []
        return out

    def bounds(ops):
        bp = BoundsPen(gs)
        for op, args in ops:
            getattr(bp, op)(*args)
        return bp.bounds

    x, paths, wave, xs = 0, [], None, []
    for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
        name = order[info.codepoint]; cs = contours(name)
        if name == "itilde":
            cs.sort(key=lambda c: -bounds(c)[3])
            cs = cs[1:]                                  # the font's tilde comes off ...
            sx0, _, sx1, sy1 = bounds(cs[0]); k = (sx1 - sx0) / T
            cx = x + pos.x_offset + (sx0 + sx1) / 2      # ... the mark's goes on, at the mark's ratios
            wave = wave_pts(0, 0, TW, TA, TT)
            wave_d = pts_d(wave, k, k, cx, -(sy1 + GAP * k))
        sp = SVGPathPen(gs); tp = TransformPen(sp, (1, 0, 0, -1, x + pos.x_offset, 0))
        for c in cs:
            for op, args in c:
                getattr(tp, op)(*args)
        paths.append(sp.getCommands())
        for c in cs:
            b = bounds(c); xs.append((x + pos.x_offset + b[0], x + pos.x_offset + b[2]))
        x += pos.x_advance + track
    d = re.sub(r"-?\d+\.\d+", lambda m: f"{round(float(m.group())):d}", " ".join(paths))
    wave_x = [float(v) for v in re.findall(r"[ML]([\d.\-]+) ", wave_d)]
    wave_y = [float(v) for v in re.findall(r"[ML][\d.\-]+ ([\d.\-]+)", wave_d)]
    left = min(min(a for a, _ in xs), min(wave_x)); right = max(max(b for _, b in xs), max(wave_x))
    top = -min(wave_y)                                   # the tilde is the tallest thing
    cap = 745                                            # height of the capital M in Plus Jakarta Sans Bold
    write(f"{BRAND_TS}/wordmark-data.ts", f"""// Generated by scripts/generate-brand-assets.py. Do not edit by hand.
// "{text}" in Plus Jakarta Sans Bold, kerned, tracking {track}/1000, with the mark's tilde.
// Font units, baseline at y = 0 (negative is above it). The tilde is separate so it can take the accent.

export const WORDMARK = {{
  /** Left and right ink edges, and the tilde's top, above the baseline. */
  left: {round(left)},
  right: {round(right)},
  top: {round(top)},
  /** Height of the capital M and b: what `size` means. */
  cap: {cap},
  /** The a and b dip a hair below the baseline. */
  descender: 12,
  d: '{d}',
  tilde: '{wave_d}',
}} as const;
""")


if __name__ == "__main__":
    ts_geometry()
    android_resources()
    wordmark()
    print("brand assets written; mark", round(MW, 1), "x", round(MH, 1))
