#!/usr/bin/env python3
"""Generate every Mbari logo asset the app ships, from one geometry.

  python3 -m venv .venv-brand && .venv-brand/bin/pip install fonttools uharfbuzz
  brew install librsvg
  .venv-brand/bin/python scripts/generate-brand-assets.py

Writes:
  src/components/brand/wordmark-data.ts   the "mbari" outlines (Plus Jakarta Sans Bold)
  android/app/src/main/res/drawable/       splash_mark, ic_launcher_foreground, ic_launcher_monochrome
  android/app/src/main/res/mipmap-*/       adaptive icon XML and legacy PNG launcher icons
  android/app/src/main/res/values*/        brand and splash colours

The mark: a bookmark ribbon (V-notch on top) folded into an L, holding one
amber dot. Every measure is a ratio of the stroke T. Keep MARK in sync with
src/components/brand/geometry.ts.
"""
import os, re, subprocess, tempfile
import uharfbuzz as hb
from fontTools.ttLib import TTFont
from fontTools.pens.recordingPen import DecomposingRecordingPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.boundsPen import BoundsPen

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = f"{ROOT}/android/app/src/main/res"
FONT = f"{RES}/font/plus_jakarta_sans_bold.ttf"

INK, INK_ON_DARK, AMBER = "#1B1712", "#F3EEE6", "#E0962C"
# The app's own backgrounds (global.css --background), so the splash hands
# over to the first screen without a change of colour.
PAPER, NIGHT = "#F9F6F0", "#0A0A0A"

# Mark geometry, in mark units.
T, N, W, H, R = 92, 40, 272, 304, 62
DOT = (T + 84, H - T - 84)
# The ribbon's mass sits left and low; nudge right and up to look centred.
NUDGE = (5.8, -3.5)

# Android 12 splash: an icon without a background is 288dp, and must fit a
# 192dp circle. 0.465 keeps the farthest corner inside it.
SPLASH_SIZE, SPLASH_SCALE = 288, 0.465
# Adaptive launcher icon: 108dp canvas, 72dp visible. The mark takes about half
# of what shows, like the brand app icon, so a circular mask never crowds it.
ICON_SIZE, ICON_SCALE = 108, 0.132


def ribbon_d():
    return f"M0,0 L{T/2:g},{N} L{T},0 L{T},{H-T} L{W},{H-T} L{W},{H} L0,{H} Z"


def dot_d():
    cx, cy = DOT
    return f"M{cx-R},{cy} a{R},{R} 0 1,0 {2*R},0 a{R},{R} 0 1,0 {-2*R},0 Z"


def placement(size, scale):
    x = (size - W * scale) / 2 + NUDGE[0] * scale
    y = (size - H * scale) / 2 + NUDGE[1] * scale
    return round(x, 3), round(y, 3)


def vector(size, scale, ink, dot):
    x, y = placement(size, scale)
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate-brand-assets.py. Do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{size}dp"
    android:height="{size}dp"
    android:viewportWidth="{size}"
    android:viewportHeight="{size}">
    <group
        android:translateX="{x}"
        android:translateY="{y}"
        android:scaleX="{scale}"
        android:scaleY="{scale}">
        <path android:fillColor="{ink}" android:pathData="{ribbon_d()}" />
        <path android:fillColor="{dot}" android:pathData="{dot_d()}" />
    </group>
</vector>
'''


def write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)


def android_resources():
    write(f"{RES}/drawable/splash_mark.xml", vector(SPLASH_SIZE, SPLASH_SCALE, "@color/splash_mark_ink", "@color/brand_amber"))
    write(f"{RES}/drawable/ic_launcher_foreground.xml", vector(ICON_SIZE, ICON_SCALE, INK_ON_DARK, AMBER))
    write(f"{RES}/drawable/ic_launcher_monochrome.xml", vector(ICON_SIZE, ICON_SCALE, "#FFFFFFFF", "#FFFFFFFF"))
    adaptive = '''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate-brand-assets.py. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
'''
    write(f"{RES}/mipmap-anydpi-v26/ic_launcher.xml", adaptive)
    write(f"{RES}/mipmap-anydpi-v26/ic_launcher_round.xml", adaptive)
    write(f"{RES}/values/colors.xml", f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate-brand-assets.py. -->
<resources>
    <color name="brand_ink">{INK}</color>
    <color name="brand_amber">{AMBER}</color>
    <color name="ic_launcher_background">{INK}</color>
    <color name="splash_background">{PAPER}</color>
    <color name="splash_mark_ink">{INK}</color>
</resources>
''')
    write(f"{RES}/values-night/colors.xml", f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate-brand-assets.py. -->
<resources>
    <color name="splash_background">{NIGHT}</color>
    <color name="splash_mark_ink">{INK_ON_DARK}</color>
</resources>
''')

    # Legacy launchers (Android 7.x): a rounded square and a circle.
    visible = 72 / ICON_SIZE  # the part of the adaptive canvas a launcher shows
    scale = ICON_SCALE / visible * 1024 / ICON_SIZE
    for name, shape in (("ic_launcher", '<rect width="1024" height="1024" rx="228" fill="{bg}"/>'),
                        ("ic_launcher_round", '<circle cx="512" cy="512" r="512" fill="{bg}"/>')):
        x, y = placement(1024, scale)
        svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">{shape.format(bg=INK)}'
               f'<g transform="translate({x} {y}) scale({scale})"><path d="{ribbon_d()}" fill="{INK_ON_DARK}"/>'
               f'<path d="{dot_d()}" fill="{AMBER}"/></g></svg>')
        with tempfile.NamedTemporaryFile("w", suffix=".svg", delete=False) as f:
            f.write(svg)
        for density, px in (("mdpi", 48), ("hdpi", 72), ("xhdpi", 96), ("xxhdpi", 144), ("xxxhdpi", 192)):
            subprocess.run(["rsvg-convert", "-w", str(px), "-h", str(px), f.name,
                            "-o", f"{RES}/mipmap-{density}/{name}.png"], check=True)
        os.unlink(f.name)


def wordmark(text="mbari", track=-14):
    font = TTFont(FONT)
    gs, order = font.getGlyphSet(), font.getGlyphOrder()
    hbfont = hb.Font(hb.Face(hb.Blob.from_file_path(FONT)))
    buf = hb.Buffer(); buf.add_str(text); buf.guess_segment_properties()
    hb.shape(hbfont, buf, {"kern": True, "liga": False})

    def bounds(ops):
        bp = BoundsPen(gs)
        for op, args in ops:
            getattr(bp, op)(*args)
        return bp.bounds

    x, paths, dot, top, bottom = 0, [], None, 0, 0
    for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
        name = order[info.codepoint]
        pen = DecomposingRecordingPen(gs); gs[name].draw(pen)
        contours, cur = [], []
        for op, args in pen.value:
            cur.append((op, args))
            if op in ("closePath", "endPath"):
                contours.append(cur); cur = []
        b = bounds(pen.value)
        top, bottom = max(top, b[3]), min(bottom, b[1])
        if name == "i":
            # The tittle becomes the mark's amber dot.
            contours.sort(key=lambda c: -bounds(c)[3])
            tittle, contours = contours[0], contours[1:]
            x0, y0, x1, y1 = bounds(tittle)
            dot = (x + (x0 + x1) / 2, -(y0 + y1) / 2, max(x1 - x0, y1 - y0) / 2 * 1.08)
        sp = SVGPathPen(gs)
        tp = TransformPen(sp, (1, 0, 0, -1, x + pos.x_offset, 0))
        for c in contours:
            for op, args in c:
                getattr(tp, op)(*args)
        paths.append(sp.getCommands())
        x += pos.x_advance + track
    d = re.sub(r"-?\d+\.\d+", lambda m: f"{round(float(m.group())):d}", " ".join(paths))
    write(f"{ROOT}/src/components/brand/wordmark-data.ts", f'''// Generated by scripts/generate-brand-assets.py. Do not edit by hand.
// "mbari" in Plus Jakarta Sans Bold, kerned, tracking {track}/1000.
// Font units, baseline at y = 0 (negative is above it).

export const WORDMARK = {{
  advance: {round(x - track)},
  ascender: {top},
  descender: {-bottom},
  /** The tittle of the i, drawn as the mark's amber dot. */
  dot: {{cx: {dot[0]:.1f}, cy: {dot[1]:.1f}, r: {dot[2]:.1f}}},
  d: '{d}',
}} as const;
''')


if __name__ == "__main__":
    android_resources()
    wordmark()
    print("brand assets written")
