// Generated by brand/source/icons.py. Do not edit by hand.
// 24 x 24 grid, 2 px line, round caps and joins.
export type IconPrimitive =
  | {t: 'path'; d: string; fill?: boolean}
  | {t: 'circle'; cx: number; cy: number; r: number; fill?: boolean}
  | {t: 'rect'; x: number; y: number; width: number; height: number; rx: number};

export const ICON_DATA = {
  alerts: [{t: 'path', d: 'M6 16v-5a6 6 0 0 1 12 0v5'}, {t: 'path', d: 'M4.5 16h15'}, {t: 'path', d: 'M10 19.5a2 2 0 0 0 4 0'}],
  community: [{t: 'path', d: 'M4 8.5c2.7-3 5.3-3 8 0s5.3 3 8 0'}, {t: 'path', d: 'M8 20v-7'}, {t: 'path', d: 'M16 20v-4'}],
  replies: [{t: 'rect', x: 9, y: 3, width: 6, height: 11, rx: 3}, {t: 'path', d: 'M5.5 11a6.5 6.5 0 0 0 13 0'}, {t: 'path', d: 'M12 17.5V21'}],
  me: [{t: 'circle', cx: 12, cy: 8, r: 3.5}, {t: 'path', d: 'M4.5 20.5c.6-3.7 3.7-6 7.5-6s6.9 2.3 7.5 6'}],
  back: [{t: 'path', d: 'M15 5l-7 7 7 7'}],
  chevronDown: [{t: 'path', d: 'M6 9l6 6 6-6'}],
  chevronRight: [{t: 'path', d: 'M9 5l7 7-7 7'}],
  close: [{t: 'path', d: 'M6 6l12 12M18 6L6 18'}],
  plus: [{t: 'path', d: 'M12 5v14M5 12h14'}],
  arrowRight: [{t: 'path', d: 'M5 12h14'}, {t: 'path', d: 'M13 6l6 6-6 6'}],
  play: [{t: 'path', d: 'M8.5 5.5v13l10.5-6.5z', fill: true}],
  link: [{t: 'path', d: 'M10.5 13.5a4 4 0 0 0 5.7 0l2.6-2.6a4 4 0 0 0-5.7-5.7l-.9.9'}, {t: 'path', d: 'M13.5 10.5a4 4 0 0 0-5.7 0l-2.6 2.6a4 4 0 0 0 5.7 5.7l.9-.9'}],
  check: [{t: 'path', d: 'M5 12.5l4.5 4.5L19 7.5'}],
  checkCircle: [{t: 'circle', cx: 12, cy: 12, r: 9}, {t: 'path', d: 'M8 12.5l2.7 2.7L16 9.5'}],
  info: [{t: 'circle', cx: 12, cy: 12, r: 9}, {t: 'path', d: 'M12 11v5'}, {t: 'circle', cx: 12, cy: 7.8, r: 1.1, fill: true}],
  clock: [{t: 'circle', cx: 12, cy: 12, r: 9}, {t: 'path', d: 'M12 7v5l3 2'}],
  phone: [{t: 'path', d: 'M5.5 4h3.2l1.6 4-2 1.4a11 11 0 0 0 5.3 5.3l1.4-2 4 1.6v3.2a1.8 1.8 0 0 1-1.9 1.8A15.5 15.5 0 0 1 3.7 5.9 1.8 1.8 0 0 1 5.5 4z'}],
  pin: [{t: 'path', d: 'M12 21s6.5-5.6 6.5-10.5a6.5 6.5 0 0 0-13 0C5.5 15.4 12 21 12 21z'}, {t: 'circle', cx: 12, cy: 10.5, r: 2.3}],
  sliders: [{t: 'path', d: 'M4 7h9M19 7h1M4 17h1M11 17h9'}, {t: 'circle', cx: 16, cy: 7, r: 2.2}, {t: 'circle', cx: 8, cy: 17, r: 2.2}],
  search: [{t: 'circle', cx: 10.5, cy: 10.5, r: 6}, {t: 'path', d: 'M20 20l-5.2-5.2'}],
  language: [{t: 'path', d: 'M3 12c3-4.6 6-4.6 9 0s6 4.6 9 0'}],
  mail: [{t: 'rect', x: 3, y: 5, width: 18, height: 14, rx: 2}, {t: 'path', d: 'M3.8 7.5L12 13.5l8.2-6'}],
} as const satisfies Record<string, readonly IconPrimitive[]>;

export type IconName = keyof typeof ICON_DATA;
